"""Add Foreign Key

Revision ID: e38c19808455
Revises: 851689a1c8fe
Create Date: 2024-10-22 19:58:44.886795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e38c19808455'
down_revision: Union[str, None] = '851689a1c8fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderitems', sa.Column('order_id', sa.Integer(), nullable=False))
    op.add_column('orderitems', sa.Column('product_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'orderitems', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'orderitems', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orderitems', type_='foreignkey')
    op.drop_constraint(None, 'orderitems', type_='foreignkey')
    op.drop_column('orderitems', 'product_id')
    op.drop_column('orderitems', 'order_id')
    # ### end Alembic commands ###
